<?php defined( 'ABSPATH' ) or	die( 'Cheatin&#8217; uh?' ); ?>
<h1 class="hide-if-no-js"><?php _e( 'FAQ\'s Table of Content', 'rocket' ); ?></h1>
<ol class="hide-if-no-js">
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/67-what-exactly-does-wp-rocket-do?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">What exactly does WP Rocket do?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/77-my-license-has-expired-what-should-i-do?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">My license has expired, what should I do?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/66-how-many-sites-is-my-key-valid-for?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">How many sites is my key valid for?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/72-i-want-to-change-the-url-of-my-site-associated-with-my-license-what-should-i-d?utm_source=plugin&utm_medium=faq&utm_campaign=doco" target="_blank">I want to change the URL of my website associated with my license, what should I do?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/68-i-have-turned-any-of-the-basic-options-on-does-wp-rocket-work?utm_source=plugin&utm_medium=faq&utm_campaign=doc">I haven\'t turned any of the basic options on, does WP Rocket work?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/78-how-often-is-the-cache-updated?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">How often is the cache updated?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/70-does-wp-rocket-work-with-default-permalinks?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">Does WP Rocket work with default permalinks?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/71-which-web-servers-is-wp-rocket-compatible-with?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">Which web servers WP Rocket is compatible with?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/8-how-the-cache-is-preloaded?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">How is the Cache Preloaded?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/69-which-tools-should-i-use-to-measure-the-performance-of-my-site?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">Which tools should I use to measure the performance of my website?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/115-can-i-use-wp-rocket-with-sitegrounds-supercacher?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">Can I Use WP Rocket With Siteground\'s SuperCacher?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/73-is-wp-rocket-compatible-with-others-cache-plugins-like-wp-super-cache-or-w3-total-cache?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">Is WP Rocket compatible with others cache plugins like WP Super Cache or W3 Total Cache?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/75-is-wp-rocket-compatible-with-e-commerce-plugins?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">Is WP Rocket compatible with e-commerce plugins?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/76-is-wp-rocket-compatible-with-wpml-qtranslate-or-polylang?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">Is WP Rocket compatible with WPML, qTranslate or Polylang?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/74-is-wp-rocket-compatible-with-wp-touch-wordpress-mobile-pack-and-wp-mobile-detector?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">Is WP Rocket compatible with WP Touch, WordPress Mobile Pack and WP Mobile Detector?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/79-reports-from-pagespeed-and-yslow-tell-me-that-the-content-is-not-gziped-and-or-did-not-expire-what-should-i-do?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">Reports from PageSpeed and YSlow tell me that the content is not gziped and/or did not expire, what should I do?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/106-my-site-is-broken?utm_source=plugin&utm_medium=faq&utm_campaign=doc">What should I do if WP Rocket distorts my website display?</a>', 'rocket' ); ?></h2></li>
	<li><h2><?php _e( '<a href="http://docs.wp-rocket.me/article/54-exclude-pages-from-the-cache?utm_source=plugin&utm_medium=faq&utm_campaign=doc" target="_blank">How to exclude a particular page from caching?</a>', 'rocket' ); ?></h2></li>
</ol>