<?php
/**
 * Loads the WP Rocket filter catalog from filters.json and contributes it to
 * mcp_helpers_filter_catalog.
 *
 * The data lives in filters.json (auto-generated by tools/scan-hooks.php). This
 * loader only reads and registers it; regenerating the JSON never touches code.
 *
 * @package WP_Rocket\MCP
 */

defined( 'ABSPATH' ) || exit;

add_filter(
	'mcp_helpers_filter_catalog',
	static function ( array $catalog ): array {
		static $entries = null;

		if ( null === $entries ) {
			$file    = __DIR__ . '/filters.json';
			$json    = is_readable( $file ) ? file_get_contents( $file ) : '';
			$decoded = '' !== $json ? json_decode( $json, true ) : [];
			$entries = is_array( $decoded ) ? $decoded : [];
		}

		return array_merge( $catalog, $entries );
	}
);
