apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: CHANGEME
  namespace: CHANGEME
spec:
  tls:
  - hosts:
    - CHANGEME.dev.smashingcoding.com
    secretName: dev-tls
  rules:
  - host: CHANGEME.dev.smashingcoding.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: CHANGEME-wordpress
          servicePort: 443
