<?php
defined( 'ABSPATH' ) || exit;

/**
 * You can edit this file, but it will be overwritten in the next update,
 * it's an autogenerated file, depending on your account
 * or you can define these values directly in your wp-config.php file
 */
