<?php
declare( strict_types=1 );

namespace WP_Rocket\Tests\Integration\inc\Engine\Admin\RocketInsights\Recommendations\Subscriber;

use WP_Rocket\Tests\Integration\TestCase;

/**
 * Test class covering WP_Rocket\Engine\Admin\RocketInsights\Recommendations\Subscriber::render_recommendations_widget
 *
 * @group RocketInsights
 * @group Recommendations
 * @group AdminOnly
 */
class Test_RenderRecommendationsWidget extends TestCase {
	/**
	 * Transient name for recommendations.
	 *
	 * @var string
	 */
	private const TRANSIENT_NAME = 'wpr_ri_recommendations';

	/**
	 * Set up before each test.
	 *
	 * @return void
	 */
	public function set_up() {
		parent::set_up();

		// Clear transient before each test.
		delete_transient( self::TRANSIENT_NAME );

		// Enable Rocket Insights for the test.
		add_filter( 'rocket_rocket_insights_enabled', '__return_true' );

        $this->unregisterAllCallbacksExcept( 'rocket_sidebar', 'render_recommendations_widget', 10 );
	}

	/**
	 * Tear down after each test.
	 *
	 * @return void
	 */
	public function tear_down() {
		// Clear transient after each test.
		delete_transient( self::TRANSIENT_NAME );

		// Remove Rocket Insights enabled filter.
		remove_filter( 'rocket_rocket_insights_enabled', '__return_true' );

        $this->restoreWpHook( 'rocket_sidebar' );

		parent::tear_down();
	}

	/**
	 * Test that the recommendations widget renders the correct state.
	 *
	 * @dataProvider configTestData
	 *
	 * @param array $config   Test configuration.
	 * @param array $expected Expected values.
	 * @return void
	 */
	public function testShouldRenderCorrectState( $config, $expected ) {
		$this->setUpTest( $config );

		// Get the widget HTML.
		$output = $this->getActualHtml();

		$this->assertOutput( $output, $expected );
	}

    /**
     * Retrieves the actual HTML output generated by the 'rocket_sidebar' action.
     *
     * Starts output buffering, triggers the 'rocket_sidebar' action to capture its output,
     * and then returns the formatted HTML if not empty. If the output is empty, returns it as is.
     *
     * @return string The formatted HTML output or an empty string if no output was generated.
     */
    private function getActualHtml() {
		ob_start();
		do_action( 'rocket_sidebar' );
		$actual = ob_get_clean();

		return empty( $actual )
			? $actual
			: $this->format_the_html( $actual );
	}

	/**
	 * Set up the test environment based on config.
	 *
	 * @param array $config Test configuration.
	 * @return void
	 */
	private function setUpTest( array $config ): void {
		// Set up transient data if provided.
		if ( isset( $config['transient_data'] ) ) {
			set_transient( self::TRANSIENT_NAME, $config['transient_data'], DAY_IN_SECONDS );
		}
	}

	/**
	 * Assert the output matches expected values.
	 *
	 * @param string $output   The rendered HTML output.
	 * @param array|string  $expected Expected values.
	 * @return void
	 */
	private function assertOutput( string $output, $expected ): void {
		if ( ! isset( $expected['state']) ) {
			$this->assertEquals(
				$output,
				$expected,
				'Expected no output, but some HTML was rendered.'
			);
			return;
		}

		// Check the data-state attribute on the container.
		if ( isset( $expected['state'] ) ) {
			$this->assertStringContainsString(
				'data-state="' . $expected['state'] . '"',
				$output,
				"Expected data-state='{$expected['state']}' attribute not found in output."
			);
		}

		// Check for specific strings that should be present.
		if ( isset( $expected['contains'] ) ) {
			foreach ( $expected['contains'] as $string ) {
				$this->assertStringContainsString(
					$string,
					$output,
					"Expected string '{$string}' not found in output."
				);
			}
		}

		// Check for specific strings that should NOT be present.
		if ( isset( $expected['not_contains'] ) ) {
			foreach ( $expected['not_contains'] as $string ) {
				$this->assertStringNotContainsString(
					$string,
					$output,
					"Unexpected string '{$string}' found in output."
				);
			}
		}

		// Check recommendation count by counting the item container divs.
		if ( isset( $expected['recommendation_count'] ) ) {
			// Count actual item containers (class="wpr-recommendation-item" at start of element).
			$count = preg_match_all( '/class="wpr-recommendation-item"/', $output );
			$this->assertSame(
				$expected['recommendation_count'],
				$count,
				"Expected {$expected['recommendation_count']} recommendations, found {$count}."
			);
		}

		// Check for Load More button.
		if ( isset( $expected['show_load_more'] ) ) {
			if ( $expected['show_load_more'] ) {
				$this->assertStringContainsString(
					'wpr-recommendations__load-more',
					$output,
					'Expected Load More button not found.'
				);
			} else {
				$this->assertStringNotContainsString(
					'wpr-recommendations__load-more',
					$output,
					'Unexpected Load More button found.'
				);
			}
		}

		// Check impact tags.
		if ( isset( $expected['impact_tags'] ) ) {
			foreach ( $expected['impact_tags'] as $tag ) {
				$this->assertStringContainsString(
					$tag,
					$output,
					"Expected impact tag '{$tag}' not found in output."
				);
			}
		}
	}
}
