<?php
/**
 * Tests for rocket_deactivation().
 *
 * @package WP_Rocket\Tests\Integration\inc\functions
 * @author  Caspar Green
 * @since   ver 3.6.1
 */

namespace WP_Rocket\Tests\Integration\inc\functions;

use Brain\Monkey\Expectation\Exception\ExpectationArgsRequired;
use Brain\Monkey\Functions;
use WP_Rocket\Tests\Integration\FilesystemTestCase;

/**
 * Tests for rocket_deactivation().
 *
 * @package WP_Rocket\Tests\Integration\inc\functions
 * @covers ::rocket_deactivation()
 * @author  Caspar Green
 * @since   ver 3.6.1
 */
class Test_RocketDeactivation extends FilesystemTestCase {
	protected $path_to_test_data = '/inc/functions/rocketDeactivation.php';

	/**
	 * Setup before running these tests.
	 *
	 * @return void
	 * @since  ver 3.6.1
	 *
	 * @author Caspar Green
	 */
	public static function setUpBeforeClass() {
		parent::setUpBeforeClass();

		require_once WP_ROCKET_PLUGIN_ROOT . 'inc/functions/deactivation.php';
	}

	/**
	 * Set up before each test.
	 *
	 * @return void
	 * @since  ver 3.6.1
	 *
	 * @author Caspar Green
	 */
	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub

		Functions\when( 'rocket_delete_config_file' )->justReturn();
	}

	/**
	 * Test should not call cleanup functions when WP_ROCKET_CONFIG_PATH is not empty.
	 *
	 * @return void
	 * @since  ver 3.6.1
	 *
	 * @author Caspar Green
	 */
	public function testShouldNotCallCleanUpFunctionsWhenRocketConfigPathNotEmpty() {
		Functions\expect( 'flush_rocket_htaccess' )
			->never();
		Functions\expect( 'set_rocket_wp_cache_define' )
			->never();
		Functions\expect( 'rocket_put_content' )
			->never();

		rocket_deactivation();
	}

	/**
	 * Test should call cleanup functions when WP_ROCKET_CONFIG_PATH is empty.
	 *
	 * @return void
	 *
	 * @throws ExpectationArgsRequired
	 * @since  ver 3.6.1
	 *
	 * @author Caspar Green
	 */
	public function testShouldCallCleanUpFunctionsWhenRocketConfigPathEmpty() {
		Functions\stubs(
			[
				'rocket_delete_config_file' => function () {
					{
						$this->filesystem->delete( 'vfs://public/wp-content/wp-rocket-config/example.org.php' );
					};
				},
			]
		);

		Functions\expect( 'flush_rocket_htaccess' )
			->once()
			->with( true )->andReturn();
		Functions\expect( 'set_rocket_wp_cache_define' )
			->once()
			->with( false )
			->andReturn();
		Functions\expect( 'rocket_put_content' )
			->once()
			->with( rocket_get_constant( 'WP_CONTENT_DIR' ) . '/advanced-cache.php', '' )
			->andReturn();

		rocket_deactivation();
	}
}
