name: PHPStan

on:
  pull_request:
  workflow_dispatch:

# Cancel all previous workflow runs for the same branch that have not yet completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: wp-media/workflows/.github/workflows/phpstan.yml@a678fad8471e1f47e6b827834baf90b91f6bb18a
