name: Unit/Integration General tests Latest version with coverage

on:
  pull_request:
    branches:
      - trunk
      - develop
      - branch-*
      - feature/*
      - enhancement/*
      - fix/*

# Cancel all previous workflow runs for the same branch that have not yet completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.4']
        wp-versions: ['latest']

    name: WP ${{ matrix.wp-versions }} with PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}.

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --default-authentication-plugin=mysql_native_password
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      WP_TESTS_DIR: "/tmp/tests/phpunit"
      WP_CORE_DIR: "/tmp/wordpress-develop"
      ROCKETCDN_EMAIL: ${{ secrets.ROCKETCDN_EMAIL }}
      ROCKETCDN_PWD: ${{ secrets.ROCKETCDN_PWD }}
      ROCKETCDN_TOKEN: ${{ secrets.ROCKETCDN_TOKEN }}
      ROCKETCDN_URL: ${{ secrets.ROCKETCDN_URL }}
      ROCKETCDN_WEBSITE_ID: ${{ secrets.ROCKETCDN_WEBSITE_ID }}
      ROCKET_EMAIL: ${{ secrets.ROCKET_EMAIL }}
      ROCKET_KEY: ${{ secrets.ROCKET_KEY }}
      ROCKET_CLOUDFLARE_API_KEY: ${{ secrets.ROCKET_CLOUDFLARE_API_KEY }}
      ROCKET_CLOUDFLARE_EMAIL: ${{ secrets.ROCKET_CLOUDFLARE_EMAIL }}
      ROCKET_CLOUDFLARE_SITE_URL: ${{ secrets.ROCKET_CLOUDFLARE_SITE_URL }}
      ROCKET_CLOUDFLARE_ZONE_ID: ${{ secrets.ROCKET_CLOUDFLARE_ZONE_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
        tools: composer:v2

    - name: Install SVN
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion

    - name: Setup problem matchers for PHP
      run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

    - name: Setup problem matchers for PHPUnit
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install dependencies
      uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
      with:
        composer-options: "--no-scripts"

    - name: Require phpcov for coverage reporting
      run: composer require --dev --no-scripts phpunit/phpcov -W

    - name: Cache WordPress test suite
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          /tmp/wordpress-develop
          /tmp/tests
        key: wp-tests-${{ runner.os }}-wp${{ matrix.wp-versions }}-${{ hashFiles('bin/install-wp-tests.sh') }}

    - name: Install tests
      run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:3306 ${{ matrix.wp-versions }}

    - name: Test
      run: composer run-tests-coverage

    - name: Code Coverage Report
      run: composer report-code-coverage

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: tests/report/coverage.clover
